import localFont from "next/font/local";
import "./globals.css";
import Aside from "@/components/Aside/Aside";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";
import ContextData from "@/Providers/Context/ContextData";
import ThemeProvider from "@/Providers/Tehme/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} bg-white dark:bg-[#171717]  ${geistMono.variable} antialiased`}
      >
      <ContextData>
        <ThemeProvider>
        <Header />

<div className="flex  items-start  ">
<Aside/>
          <section className="w-full pl-5   min-h-screen mx-auto dark:bg-[#101010] bg-[--main-color]   ">
           
            <div className="py-2">
            {children}
            </div>

          </section>
      </div>
        </ThemeProvider>
    
      </ContextData>
      <Toaster />

      </body>
    </html>
  );
}
