import localFont from "next/font/local";
import "./globals.css";
import Aside from "@/components/Aside/Aside";
import Header from "@/components/Header/Header";
import ContextData from "@/Context/ContextData";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ContextData>
      <div className="flex  items-start  ">
      <Aside/>
                <section className="w-full min-h-screen  bg-[--main-color]   ">
                  <Header />
                  <div className="p-4">
                  {children}
                  </div>
      
                </section>
            </div>
      </ContextData>
      <Toaster />

      </body>
    </html>
  );
}
